#include <os64.h>
#include <os64/libc.h>
#include <string.h>
static const os64_api_t*api;
static const char supported[]="ls cp mv rm mkdir touch pwd find stat cat head tail wc uname date time whoami ps mount sync ping ifconfig ip sh echo history clear grep cmp true false hostname id env printenv which";
static void out(const char*s){api->write(s);}static int word(const char**p,char*b,unsigned cap){while(**p==' ')*p+=1;unsigned n=0;while(**p&&**p!=' '&&n+1<cap)b[n++]=*(*p)++;b[n]=0;return n!=0;}
static int listed(const char*n){const char*p=supported;char b[24];while(word(&p,b,sizeof b))if(!strcmp(n,b))return 1;return 0;}
static int grep_applet(const char*a){char needle[64],path[128];if(!word(&a,needle,sizeof needle)||!word(&a,path,sizeof path)){out("Usage: busybox grep PATTERN FILE\n");return 2;}unsigned char data[4096];os64_size_t n;if(!api->read_file(path,data,sizeof data,&n)){out("grep: cannot read file\n");return 1;}int matched=0;for(os64_size_t start=0;start<n;){os64_size_t end=start;while(end<n&&data[end]!='\n')end++;for(os64_size_t i=start;i+strlen(needle)<=end;i++)if(!memcmp(data+i,needle,strlen(needle))){for(os64_size_t j=start;j<end;j++)api->putc((char)data[j]);api->putc('\n');matched=1;break;}start=end+1;}return matched?0:1;}
static int cmp_applet(const char*a){char x[128],y[128];if(!word(&a,x,sizeof x)||!word(&a,y,sizeof y)){out("Usage: busybox cmp FILE1 FILE2\n");return 2;}unsigned char p[4096],q[4096];os64_size_t pn,qn;if(!api->read_file(x,p,sizeof p,&pn)||!api->read_file(y,q,sizeof q,&qn)){out("cmp: cannot read file\n");return 1;}if(pn==qn&&!memcmp(p,q,pn))return 0;out("cmp: files differ\n");return 1;}
static int help(const char*n){if(n&&*n){out("OS64 BusyBox applet: ");out(n);out("\nUse APPLET --help for kernel utility help.\n");return 0;}out("OS64 BusyBox 1.0 multicall utility\nUsage: busybox APPLET [ARGUMENTS...]\n       busybox --list\n\nSupported applets:\n");out(supported);out("\n\nUnavailable until OS64 gains pipes/processes/codecs: tar gzip xz unzip top nice nc wget tee sort uniq cut paste tr diff less more.\n");return 0;}
int _start(const os64_api_t*a,const char*args){if(!a||a->version<5)return 126;api=a;os64_libc_init(a);char applet[24];if(!word(&args,applet,sizeof applet))return help(0);if(!strcmp(applet,"--help"))return help(0);if(!strcmp(applet,"--version")){out("OS64 BusyBox 1.0\n");return 0;}if(!strcmp(applet,"--list")){out(supported);out("\n");return 0;}while(*args==' ')args++;if(!strcmp(applet,"grep"))return grep_applet(args);if(!strcmp(applet,"cmp"))return cmp_applet(args);if(!strcmp(applet,"true"))return 0;if(!strcmp(applet,"false"))return 1;if(!strcmp(applet,"hostname")){out("os64\n");return 0;}if(!strcmp(applet,"id")){out(!strcmp(api->current_user(),"root")?"uid=0(root) gid=0(root)\n":"uid=1000(user) gid=100(users)\n");return 0;}if(!strcmp(applet,"env")||!strcmp(applet,"printenv")){out("PATH=/bin:/sbin:/usr/bin:/usr/sbin\nHOME=/root\nSHELL=/bin/sh\n");return 0;}if(!strcmp(applet,"which")){char n[24];if(!word(&args,n,sizeof n)||!listed(n))return 1;out("/bin/");out(n);out("\n");return 0;}if(!strcmp(applet,"rmdir"))applet[0]='r',applet[1]='m',applet[2]=0;if(listed(applet))return api->dispatch(applet,args);out("busybox: applet '");out(applet);out("' is not available on this OS64 build\n");return 127;}
