#include "auth.h"
#include "crypto.h"
#include <stdint.h>
typedef struct{char user[16],salt[32];uint8_t hash[32];int locked;uint16_t uid,gid;auth_role_t role;uint32_t groups;}record_t;
static record_t records[16];static size_t users,current;static uint16_t current_umask=0022;
static int eq(const char*a,const char*b){while(*a&&*a==*b){a++;b++;}return !*a&&!*b;}static int hex(char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;}
static void defaults(record_t*r,size_t index){r->uid=(uint16_t)(1000+index);r->gid=100;r->role=AUTH_STANDARD;r->groups=AUTH_GROUP_USERS;if(eq(r->user,"root")){r->uid=r->gid=0;r->role=AUTH_ROOT;r->groups=AUTH_GROUP_ROOT|AUTH_GROUP_ADMIN|AUTH_GROUP_WHEEL|AUTH_GROUP_STORAGE|AUTH_GROUP_NETWORK;}else if(eq(r->user,"nobody")){r->uid=r->gid=65534;r->role=AUTH_GUEST;r->groups=0;}}
static record_t*find(const char*u){for(size_t i=0;i<users;i++)if(eq(u,records[i].user))return &records[i];return 0;}
static void hash_password(record_t*r,const char*p){const char*pre="os64-user-";size_t n=0;while(pre[n]){r->salt[n]=pre[n];n++;}for(size_t i=0;r->user[i]&&n<31;i++)r->salt[n++]=r->user[i];r->salt[n]=0;size_t pn=0;while(p[pn])pn++;pbkdf2_sha256((const uint8_t*)p,pn,(const uint8_t*)r->salt,n,10000,r->hash);r->locked=0;}
static int parse_line(const unsigned char*d,size_t start,size_t end){if(users>=16)return 0;size_t c=start;while(c<end&&d[c]!=':')c++;if(c==start||c==end)return 0;record_t*r=&records[users];for(size_t i=0;i<sizeof *r;i++)((uint8_t*)r)[i]=0;size_t u=c-start;if(u>15)u=15;for(size_t i=0;i<u;i++)r->user[i]=(char)d[start+i];r->user[u]=0;defaults(r,users);c++;r->locked=c<end&&d[c]=='!';if(r->locked){users++;return 1;}const char*prefix="$pbkdf2-sha256$10000$";for(size_t i=0;prefix[i];i++)if(c>=end||d[c++]!=(unsigned char)prefix[i])return 0;size_t s=0;while(c<end&&d[c]!='$'&&s<31)r->salt[s++]=(char)d[c++];r->salt[s]=0;if(c>=end||d[c++]!='$')return 0;for(int i=0;i<32;i++){if(c+1>=end)return 0;int a=hex((char)d[c++]),b=hex((char)d[c++]);if(a<0||b<0)return 0;r->hash[i]=(uint8_t)((a<<4)|b);}users++;return 1;}
int auth_load(const unsigned char*d,size_t n){users=current=0;size_t i=0;while(i<n){size_t s=i;while(i<n&&d[i]!='\n')i++;if(i>s&&d[s]!='#'&&!parse_line(d,s,i))return 0;i++;}auth_select("root");return users>0;}
size_t auth_user_count(void){return users;}int auth_check(const char*u,const char*p){record_t*r=find(u);if(!r||r->locked)return 0;size_t pn=0,sn=0;while(p[pn])pn++;while(r->salt[sn])sn++;uint8_t got[32];pbkdf2_sha256((const uint8_t*)p,pn,(const uint8_t*)r->salt,sn,10000,got);uint8_t diff=0;for(int n=0;n<32;n++)diff|=got[n]^r->hash[n];return diff==0;}int auth_nologin(const char*u){record_t*r=find(u);return !r||r->locked;}
int auth_add_role(const char*u,const char*p,auth_role_t role){if(users>=16||find(u)||role<AUTH_ROOT||role>AUTH_GUEST)return 0;record_t*r=&records[users];for(size_t i=0;i<sizeof *r;i++)((uint8_t*)r)[i]=0;size_t n=0;while(u[n]&&n<15){r->user[n]=u[n];n++;}r->user[n]=0;defaults(r,users);r->role=role;if(role==AUTH_ADMIN)r->groups|=AUTH_GROUP_ADMIN|AUTH_GROUP_WHEEL|AUTH_GROUP_NETWORK|AUTH_GROUP_OPERATORS;else if(role==AUTH_POWER)r->groups|=AUTH_GROUP_DEVELOPERS|AUTH_GROUP_OPERATORS;else if(role==AUTH_GUEST){r->groups=0;r->gid=65534;}hash_password(r,p);users++;return 1;}int auth_add(const char*u,const char*p){return auth_add_role(u,p,AUTH_STANDARD);}
int auth_delete(const char*u){record_t*r=find(u);if(!r||r->uid==0)return 0;size_t at=(size_t)(r-records);for(size_t i=at;i+1<users;i++)records[i]=records[i+1];users--;if(current>=users)current=0;return 1;}int auth_set_password(const char*u,const char*p){record_t*r=find(u);if(!r)return 0;hash_password(r,p);return 1;}int auth_set_role(const char*u,auth_role_t role){record_t*r=find(u);if(!r||r->uid==0||role==AUTH_ROOT)return 0;r->role=role;return 1;}int auth_set_groups(const char*u,uint32_t g){record_t*r=find(u);if(!r||r->uid==0)return 0;r->groups=g|AUTH_GROUP_USERS;return 1;}
int auth_select(const char*u){record_t*r=find(u);if(!r)return 0;current=(size_t)(r-records);current_umask=r->role==AUTH_GUEST?0077:0022;return 1;}int auth_select_uid(uint16_t uid){for(size_t i=0;i<users;i++)if(records[i].uid==uid)return auth_select(records[i].user);return 0;}const char*auth_current_user(void){return users?records[current].user:"nobody";}uint16_t auth_getuid(void){return users?records[current].uid:65534;}uint16_t auth_getgid(void){return users?records[current].gid:65534;}uint32_t auth_getgroups(void){return users?records[current].groups:0;}auth_role_t auth_current_role(void){return users?records[current].role:AUTH_GUEST;}int auth_is_root(void){return auth_getuid()==0;}int auth_is_admin(void){return auth_is_root()||auth_current_role()==AUTH_ADMIN||auth_has_group(AUTH_GROUP_ADMIN);}int auth_has_group(uint32_t g){return (auth_getgroups()&g)!=0;}
int auth_lookup(const char*u,uint16_t*uid,uint16_t*gid,auth_role_t*role,uint32_t*groups){record_t*r=find(u);if(!r)return 0;if(uid)*uid=r->uid;if(gid)*gid=r->gid;if(role)*role=r->role;if(groups)*groups=r->groups;return 1;}
const char*auth_role_name(auth_role_t r){return r==AUTH_ROOT?"root":r==AUTH_ADMIN?"administrator":r==AUTH_POWER?"power":r==AUTH_STANDARD?"standard":"guest";}static const char*group_names[]={"root","admin","users","developers","operators","network","audio","video","storage","wheel"};uint32_t auth_group_from_name(const char*n){for(unsigned i=0;i<10;i++)if(eq(n,group_names[i]))return 1u<<i;return 0;}const char*auth_group_name(unsigned i){return i<10?group_names[i]:0;}uint16_t auth_umask(void){return current_umask;}void auth_set_umask(uint16_t m){current_umask=m&0777;}
static int putnum(unsigned char*d,size_t cap,size_t*n,uint32_t v){char b[12];unsigned z=0;if(!v)b[z++]='0';while(v){b[z++]=(char)('0'+v%10);v/=10;}while(z){if(*n>=cap)return 0;d[(*n)++]=(unsigned char)b[--z];}return 1;}
size_t auth_export_shadow(unsigned char*d,size_t cap){const char*h="0123456789abcdef";size_t n=0;for(size_t i=0;i<users;i++){record_t*r=&records[i];for(size_t j=0;r->user[j];j++){if(n>=cap)return 0;d[n++]=(unsigned char)r->user[j];}if(n>=cap)return 0;d[n++]=':';if(r->locked){if(n+2>cap)return 0;d[n++]='!';d[n++]='\n';continue;}const char*p="$pbkdf2-sha256$10000$";for(size_t j=0;p[j];j++){if(n>=cap)return 0;d[n++]=(unsigned char)p[j];}for(size_t j=0;r->salt[j];j++){if(n>=cap)return 0;d[n++]=(unsigned char)r->salt[j];}if(n>=cap)return 0;d[n++]='$';for(int j=0;j<32;j++){if(n+2>cap)return 0;d[n++]=h[r->hash[j]>>4];d[n++]=h[r->hash[j]&15];}if(n>=cap)return 0;d[n++]='\n';}return n;}
size_t auth_export_accounts(unsigned char*d,size_t cap){size_t n=0;for(size_t i=0;i<users;i++){record_t*r=&records[i];for(size_t j=0;r->user[j];j++){if(n>=cap)return 0;d[n++]=(unsigned char)r->user[j];}if(n>=cap)return 0;d[n++]=':';if(!putnum(d,cap,&n,r->uid)||n>=cap)return 0;d[n++]=':';if(!putnum(d,cap,&n,r->gid)||n>=cap)return 0;d[n++]=':';if(!putnum(d,cap,&n,(uint32_t)r->role)||n>=cap)return 0;d[n++]=':';if(!putnum(d,cap,&n,r->groups)||n>=cap)return 0;d[n++]='\n';}return n;}
static uint32_t number(const unsigned char*d,size_t*at,size_t end){uint32_t v=0;while(*at<end&&d[*at]>='0'&&d[*at]<='9'){v=v*10u+d[(*at)++]-'0';}return v;}int auth_load_accounts(const unsigned char*d,size_t n){size_t at=0;while(at<n){size_t s=at;while(at<n&&d[at]!=':'&&d[at]!='\n')at++;char u[16];size_t z=0;while(s<at&&z<15)u[z++]=(char)d[s++];u[z]=0;if(at>=n||d[at++]!=':')return 0;record_t*r=find(u);if(!r){while(at<n&&d[at++]!='\n');continue;}r->uid=(uint16_t)number(d,&at,n);if(at>=n||d[at++]!=':')return 0;r->gid=(uint16_t)number(d,&at,n);if(at>=n||d[at++]!=':')return 0;r->role=(auth_role_t)number(d,&at,n);if(at>=n||d[at++]!=':')return 0;r->groups=number(d,&at,n);while(at<n&&d[at++]!='\n');}return 1;}
