#include "image_viewer.h"
#include "compositor.h"
#include "display.h"
#include "memory.h"
#include "vfs.h"
#include <stdint.h>
#define IMAGE_FILE_LIMIT (1024u*1024u)
static void text(char*d,const char*s){unsigned n=0;while(s&&s[n]&&n<79){d[n]=s[n];n++;}d[n]=0;}
static uint16_t le16(const unsigned char*p){return (uint16_t)(p[0]|((uint16_t)p[1]<<8));}
static uint32_t le32(const unsigned char*p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static int token(image_document_t*i,size_t*at,unsigned*out){while(*at<i->size){unsigned char c=i->data[*at];if(c=='#'){while(*at<i->size&&i->data[*at]!='\n')(*at)++;continue;}if(c==' '||c=='\t'||c=='\r'||c=='\n'){(*at)++;continue;}break;}if(*at>=i->size||i->data[*at]<'0'||i->data[*at]>'9')return 0;unsigned v=0;while(*at<i->size&&i->data[*at]>='0'&&i->data[*at]<='9'){if(v>1000000)return 0;v=v*10u+(unsigned)(i->data[(*at)++]-'0');}*out=v;return 1;}
void image_document_init(image_document_t*i){if(!i)return;i->data=0;i->size=i->offset=i->stride=0;i->width=i->height=i->max_value=i->bpp=0;i->top_down=0;i->format=IMAGE_NONE;text(i->status,"No image loaded. Use: view PATH");}
static int ppm(image_document_t*i){int ascii=i->data[1]=='3';if(i->size<3||i->data[0]!='P'||(!ascii&&i->data[1]!='6'))return 0;size_t p=2;unsigned w,h,max;if(!token(i,&p,&w)||!token(i,&p,&h)||!token(i,&p,&max)||!w||!h||!max||max>255||w>4096||h>4096)return 0;while(p<i->size&&(i->data[p]==' '||i->data[p]=='\t'||i->data[p]=='\r'||i->data[p]=='\n'))p++;size_t pixels=(size_t)w*h;if(pixels>IMAGE_FILE_LIMIT/3)return 0;if(ascii){for(size_t n=0;n<pixels*3;n++){unsigned value;if(!token(i,&p,&value)||value>max)return 0;i->data[n]=(unsigned char)value;}i->offset=0;i->size=pixels*3;}else{if(pixels*3>i->size-p)return 0;i->offset=p;}i->width=w;i->height=h;i->max_value=max;i->stride=(size_t)w*3;i->bpp=24;i->top_down=1;i->format=IMAGE_PPM;text(i->status,ascii?"PPM P3":"PPM P6");return 1;}
static int bmp(image_document_t*i){if(i->size<54||i->data[0]!='B'||i->data[1]!='M'||le32(i->data+14)<40)return 0;int32_t w=(int32_t)le32(i->data+18),h=(int32_t)le32(i->data+22);unsigned bpp=le16(i->data+28),compression=le32(i->data+30);size_t off=le32(i->data+10);if(w<=0||h==0||w>4096||h>4096||h<-4096||(bpp!=24&&bpp!=32)||compression||off>=i->size)return 0;unsigned height=(unsigned)(h<0?-h:h);size_t stride=((size_t)(unsigned)w*(bpp/8)+3)&~(size_t)3;if(stride*height>i->size-off)return 0;i->width=(unsigned)w;i->height=height;i->offset=off;i->stride=stride;i->bpp=bpp;i->max_value=255;i->top_down=h<0;i->format=IMAGE_BMP;text(i->status,bpp==24?"BMP 24-bit":"BMP 32-bit");return 1;}
int image_open(image_document_t*i,const char*path){if(!i||!path)return 0;image_close(i);vfs_stat_t st;if(!vfs_stat_path(path,&st)||st.type!=VFS_TYPE_FILE||!st.size||st.size>IMAGE_FILE_LIMIT){text(i->status,"Image not found or larger than 1 MiB.");return 0;}i->data=kmalloc(st.size);if(!i->data){text(i->status,"Not enough memory to open image.");return 0;}size_t n;if(!vfs_read(path,i->data,st.size,&n,&st)||n!=st.size){image_close(i);text(i->status,"Could not read image file.");return 0;}i->size=n;if(ppm(i)||bmp(i))return 1;image_close(i);text(i->status,"Unsupported image. Use PPM P3/P6 or BMP 24/32-bit.");return 0;}
void image_close(image_document_t*i){if(!i)return;if(i->data)kfree(i->data);i->data=0;i->format=IMAGE_NONE;i->size=0;}
static uint32_t pixel(const image_document_t*i,unsigned x,unsigned y){const unsigned char*p;if(i->format==IMAGE_PPM){p=i->data+i->offset+(size_t)y*i->stride+(size_t)x*3;unsigned r=p[0],g=p[1],b=p[2];if(i->max_value!=255){r=r*255/i->max_value;g=g*255/i->max_value;b=b*255/i->max_value;}return (r<<16)|(g<<8)|b;}unsigned row=i->top_down?y:i->height-1-y;p=i->data+i->offset+(size_t)row*i->stride+(size_t)x*(i->bpp/8);return ((uint32_t)p[2]<<16)|((uint32_t)p[1]<<8)|p[0];}
void image_render(const image_document_t*i,int x,int y,int w,int h){compositor_fill(x,y,w,h,0x10141a);if(!i||i->format==IMAGE_NONE){compositor_text(x+18,y+20,i?i->status:"No image",(unsigned)(w>36?(w-36)/8:1),0xd7dee8,0x10141a);return;}int aw=w-20,ah=h-42;if(aw<=0||ah<=0)return;unsigned dw=i->width,dh=i->height;if(dw>(unsigned)aw){dh=(unsigned)((uint64_t)dh*(unsigned)aw/dw);dw=(unsigned)aw;}if(dh>(unsigned)ah){dw=(unsigned)((uint64_t)dw*(unsigned)ah/dh);dh=(unsigned)ah;}if(!dw||!dh)return;int ox=x+(w-(int)dw)/2,oy=y+8+(ah-(int)dh)/2;for(unsigned py=0;py<dh;py++)for(unsigned px=0;px<dw;px++){unsigned sx=(unsigned)((uint64_t)px*i->width/dw),sy=(unsigned)((uint64_t)py*i->height/dh);display_graphics_put_pixel((unsigned)(ox+(int)px),(unsigned)(oy+(int)py),pixel(i,sx,sy));}char info[64];unsigned n=0;const char*s=i->status;while(*s&&n<40)info[n++]=*s++;info[n++]=' ';unsigned values[2]={i->width,i->height};for(unsigned z=0;z<2;z++){char r[12];unsigned q=0,v=values[z];if(!v)r[q++]='0';while(v){r[q++]=(char)('0'+v%10);v/=10;}while(q&&n+1<sizeof info)info[n++]=r[--q];if(!z)info[n++]='x';}info[n]=0;compositor_text(x+10,y+h-24,info,(unsigned)(w>20?(w-20)/8:1),0xb9c5d1,0x10141a);}
