#include "window_manager.h"
static void copy(char*d,const char*s,unsigned cap){unsigned n=0;while(s&&s[n]&&n+1<cap){d[n]=s[n];n++;}d[n]=0;}
unsigned wm_count(const window_manager_t*wm){unsigned n=0;for(unsigned i=0;i<WM_MAX_WINDOWS;i++)if(wm->windows[i].used)n++;return n;}
unsigned wm_focused(const window_manager_t*wm){for(unsigned i=0;i<WM_MAX_WINDOWS;i++)if(wm->windows[i].used&&wm->windows[i].focused)return wm->windows[i].id;return 0;}
wm_window_t*wm_by_id(window_manager_t*wm,unsigned id){for(unsigned i=0;i<WM_MAX_WINDOWS;i++)if(wm->windows[i].used&&wm->windows[i].id==id)return &wm->windows[i];return 0;}
static void tile(window_manager_t*wm){if(wm->layout!=WM_LAYOUT_TILED)return;unsigned n=wm_count(wm),seen=0;if(!n)return;int x=8,y=44,w=(int)wm->screen_width-16,h=(int)wm->screen_height-96;for(unsigned i=0;i<WM_MAX_WINDOWS;i++)if(wm->windows[i].used){wm_window_t*v=&wm->windows[i];if(n==1){v->x=x;v->y=y;v->width=w;v->height=h;}else if(!seen){v->x=x;v->y=y;v->width=w*3/5-3;v->height=h;}else{int rw=w-w*3/5-3;int rh=h/(int)(n-1);v->x=x+w*3/5+3;v->y=y+(int)(seen-1)*rh;v->width=rw;v->height=seen==n-1?y+h-v->y:rh-3;}seen++;}}
void wm_init(window_manager_t*wm,unsigned width,unsigned height){wm->screen_width=width;wm->screen_height=height;wm->next_id=1;wm->layout=WM_LAYOUT_FLOATING;for(unsigned i=0;i<WM_MAX_WINDOWS;i++)wm->windows[i].used=0;}
wm_window_t*wm_create(window_manager_t*wm,const char*title,void*client){unsigned slot=WM_MAX_WINDOWS;for(unsigned i=0;i<WM_MAX_WINDOWS;i++)if(!wm->windows[i].used){slot=i;break;}if(slot==WM_MAX_WINDOWS)return 0;for(unsigned i=0;i<WM_MAX_WINDOWS;i++)wm->windows[i].focused=0;wm_window_t*w=&wm->windows[slot];w->used=w->focused=1;w->id=wm->next_id++;w->x=36+(int)slot*28;w->y=54+(int)slot*24;w->width=(int)wm->screen_width-144;w->height=(int)wm->screen_height-160;w->client=client;copy(w->title,title,sizeof w->title);tile(wm);return w;}
void wm_close(window_manager_t*wm,unsigned id){wm_window_t*w=wm_by_id(wm,id);if(!w)return;w->used=w->focused=0;for(int i=WM_MAX_WINDOWS-1;i>=0;i--)if(wm->windows[i].used){wm->windows[i].focused=1;break;}tile(wm);}
void wm_focus(window_manager_t*wm,unsigned id){if(!wm_by_id(wm,id))return;for(unsigned i=0;i<WM_MAX_WINDOWS;i++)wm->windows[i].focused=wm->windows[i].used&&wm->windows[i].id==id;}
void wm_focus_next(window_manager_t*wm){unsigned current=wm_focused(wm),candidate=0;for(unsigned i=0;i<WM_MAX_WINDOWS;i++)if(wm->windows[i].used&&wm->windows[i].id>current&&(candidate==0||wm->windows[i].id<candidate))candidate=wm->windows[i].id;if(!candidate)for(unsigned i=0;i<WM_MAX_WINDOWS;i++)if(wm->windows[i].used&&(candidate==0||wm->windows[i].id<candidate))candidate=wm->windows[i].id;if(candidate)wm_focus(wm,candidate);}
void wm_toggle_layout(window_manager_t*wm){wm->layout=wm->layout==WM_LAYOUT_TILED?WM_LAYOUT_FLOATING:WM_LAYOUT_TILED;tile(wm);}
void wm_move(window_manager_t*wm,unsigned id,int x,int y){wm_window_t*w=wm_by_id(wm,id);if(!w||wm->layout!=WM_LAYOUT_FLOATING)return;if(x<0)x=0;if(y<36)y=36;if(x+w->width>(int)wm->screen_width)x=(int)wm->screen_width-w->width;if(y+w->height>(int)wm->screen_height-44)y=(int)wm->screen_height-44-w->height;w->x=x;w->y=y;}
wm_window_t*wm_at(window_manager_t*wm,int x,int y){for(unsigned i=0;i<WM_MAX_WINDOWS;i++){wm_window_t*w=&wm->windows[i];if(w->used&&w->focused&&x>=w->x&&y>=w->y&&x<w->x+w->width&&y<w->y+w->height)return w;}for(int i=WM_MAX_WINDOWS-1;i>=0;i--){wm_window_t*w=&wm->windows[i];if(w->used&&x>=w->x&&y>=w->y&&x<w->x+w->width&&y<w->y+w->height)return w;}return 0;}
