#include "ansi_terminal.h"
#include "display.h"
#define MW 216u
#define MH 64u
struct cell{uint32_t cp;uint8_t attr;};
static struct cell front[MW*MH],back[MW*MH];
static unsigned width,height,row,col,saved_row,saved_col,scroll_top,scroll_bottom,params[8],param_count,param_value;
static uint8_t fg=7,bg,state,private_mode,bold,cursor_visible=1,utf8_left;static uint32_t utf8_cp;static int initialized,dirty;
static uint8_t cp437(uint32_t u){switch(u){case 0x2502:return 179;case 0x2524:return 180;case 0x2563:return 185;case 0x2551:return 186;case 0x2557:return 187;case 0x255d:return 188;case 0x2510:return 191;case 0x2514:return 192;case 0x2534:return 193;case 0x252c:return 194;case 0x251c:return 195;case 0x2500:return 196;case 0x253c:return 197;case 0x255a:return 200;case 0x2554:return 201;case 0x2569:return 202;case 0x2566:return 203;case 0x2560:return 204;case 0x2550:return 205;case 0x256c:return 206;case 0x2518:return 217;case 0x250c:return 218;case 0x2588:return 219;case 0x2591:return 176;case 0x2592:return 177;case 0x2593:return 178;default:return u<128?(uint8_t)u:'?';}}
static uint8_t attr(void){return (uint8_t)((bg&15)<<4|(fg&7)|(bold||fg>=8?8:0));}
static void mark(unsigned x,unsigned y,uint32_t cp){if(x>=width||y>=height)return;back[y*MW+x].cp=cp;back[y*MW+x].attr=attr();dirty=1;}
static void scroll(void){if(row<=scroll_bottom)return;for(unsigned y=scroll_top+1;y<=scroll_bottom;y++)for(unsigned x=0;x<width;x++)back[(y-1)*MW+x]=back[y*MW+x];for(unsigned x=0;x<width;x++){back[scroll_bottom*MW+x].cp=' ';back[scroll_bottom*MW+x].attr=attr();}row=scroll_bottom;dirty=1;}
static void emit(uint32_t cp){if(cp=='\r'){col=0;return;}if(cp=='\n'){col=0;row++;scroll();return;}if(cp=='\b'){if(col)col--;return;}if(cp=='\t'){unsigned n=(col+8)&~7u;while(col<n&&col<width)mark(col++,row,' ');return;}if(cp<32)return;mark(col,row,cp);if(++col>=width){col=0;row++;scroll();}}
static unsigned parameter(unsigned i,unsigned fallback){return i<param_count&&params[i]?params[i]:fallback;}
static void erase_line(unsigned mode){unsigned begin=mode==1?0:col,end=mode==0?width:col+1;if(mode==2){begin=0;end=width;}for(unsigned x=begin;x<end&&x<width;x++)mark(x,row,' ');}
static void erase_screen(unsigned mode){if(mode==2||mode==3){for(unsigned y=0;y<height;y++)for(unsigned x=0;x<width;x++)mark(x,y,' ');row=col=0;}else if(mode==0){erase_line(0);for(unsigned y=row+1;y<height;y++)for(unsigned x=0;x<width;x++)mark(x,y,' ');}else{erase_line(1);for(unsigned y=0;y<row;y++)for(unsigned x=0;x<width;x++)mark(x,y,' ');}}
static void sgr(void){if(!param_count){fg=7;bg=bold=0;return;}for(unsigned i=0;i<param_count;i++){unsigned v=params[i];if(v==0){fg=7;bg=bold=0;}else if(v==1)bold=1;else if(v==22)bold=0;else if(v>=30&&v<=37)fg=(uint8_t)(v-30);else if(v>=90&&v<=97)fg=(uint8_t)(v-90+8);else if(v>=40&&v<=47)bg=(uint8_t)(v-40);else if(v>=100&&v<=107)bg=(uint8_t)(v-100+8);else if(v==39)fg=7;else if(v==49)bg=0;else if((v==38||v==48)&&i+2<param_count&&params[i+1]==5){uint8_t c=(uint8_t)params[i+2],mapped=c<16?c:(c>=232?(c>=244?15:8):7);if(v==38)fg=mapped;else bg=mapped;i+=2;}}}
static void csi(unsigned char final){if(param_count<8)params[param_count++]=param_value;switch(final){case 'm':sgr();break;case 'H':case 'f':row=parameter(0,1)-1;col=parameter(1,1)-1;break;case 'A':{unsigned n=parameter(0,1);row=row>n?row-n:0;}break;case 'B':row+=parameter(0,1);break;case 'C':col+=parameter(0,1);break;case 'D':{unsigned n=parameter(0,1);col=col>n?col-n:0;}break;case 'J':erase_screen(parameter(0,0));break;case 'K':erase_line(parameter(0,0));break;case 's':saved_row=row;saved_col=col;break;case 'u':row=saved_row;col=saved_col;break;case 'r':scroll_top=parameter(0,1)-1;scroll_bottom=parameter(1,height)-1;if(scroll_top>=height||scroll_bottom>=height||scroll_top>=scroll_bottom){scroll_top=0;scroll_bottom=height-1;}row=scroll_top;col=0;break;case 'h':if(private_mode&&parameter(0,0)==25)cursor_visible=1;break;case 'l':if(private_mode&&parameter(0,0)==25)cursor_visible=0;break;default:break;}if(row>=height)row=height-1;if(col>=width)col=width-1;state=private_mode=param_count=param_value=0;}
void ansi_init(void){width=(unsigned)display_width();height=(unsigned)display_height();if(width>MW)width=MW;if(height>MH)height=MH;for(unsigned y=0;y<height;y++)for(unsigned x=0;x<width;x++){uint16_t v=display_cell(x,y);unsigned i=y*MW+x;back[i].cp=(uint8_t)v;back[i].attr=(uint8_t)(v>>8);front[i]=back[i];}row=col=saved_row=saved_col=0;scroll_top=0;scroll_bottom=height?height-1:0;fg=7;bg=state=private_mode=bold=utf8_left=0;cursor_visible=1;dirty=0;initialized=1;}
void ansi_reset(void){initialized=0;ansi_init();}
void ansi_putchar(unsigned char b){if(!initialized)ansi_init();if(state==1){if(b=='['){state=2;param_count=param_value=private_mode=0;}else state=0;return;}if(state==2){if(b=='?'){private_mode=1;return;}if(b>='0'&&b<='9'){param_value=param_value*10u+(unsigned)(b-'0');return;}if(b==';'){if(param_count<8)params[param_count++]=param_value;param_value=0;return;}csi(b);return;}if(b==0x1b){state=1;return;}if(utf8_left){if((b&0xc0)!=0x80){utf8_left=0;emit('?');}else{utf8_cp=(utf8_cp<<6)|(b&63);if(!--utf8_left)emit(utf8_cp);return;}}if(b<0x80)emit(b);else if((b&0xe0)==0xc0){utf8_cp=b&31;utf8_left=1;}else if((b&0xf0)==0xe0){utf8_cp=b&15;utf8_left=2;}else if((b&0xf8)==0xf0){utf8_cp=b&7;utf8_left=3;}else emit('?');}
void ansi_write(const char*s){if(!s)return;while(*s)ansi_putchar((unsigned char)*s++);ansi_flush();}void ansi_set_fg(uint8_t c){fg=c&15;}void ansi_set_bg(uint8_t c){bg=c&15;}void ansi_move_cursor(unsigned r,unsigned c){if(!initialized)ansi_init();row=r<height?r:height-1;col=c<width?c:width-1;}void ansi_clear(void){if(!initialized)ansi_init();erase_screen(2);}
void ansi_draw_box(unsigned x,unsigned y,unsigned w,unsigned h,int dbl){if(w<2||h<2)return;uint32_t hz=dbl?0x2550:0x2500,vt=dbl?0x2551:0x2502,tl=dbl?0x2554:0x250c,tr=dbl?0x2557:0x2510,bl=dbl?0x255a:0x2514,br=dbl?0x255d:0x2518;for(unsigned i=1;i+1<w;i++){mark(x+i,y,hz);mark(x+i,y+h-1,hz);}for(unsigned i=1;i+1<h;i++){mark(x,y+i,vt);mark(x+w-1,y+i,vt);}mark(x,y,tl);mark(x+w-1,y,tr);mark(x,y+h-1,bl);mark(x+w-1,y+h-1,br);}void ansi_draw_panel(unsigned x,unsigned y,unsigned w,unsigned h,const char*t){ansi_draw_box(x,y,w,h,0);if(t)for(unsigned i=0;t[i]&&i+3<w;i++)mark(x+2+i,y,(unsigned char)t[i]);}void ansi_draw_progress(unsigned x,unsigned y,unsigned w,unsigned percent){if(percent>100)percent=100;unsigned filled=w*percent/100;for(unsigned i=0;i<w;i++)mark(x+i,y,i<filled?0x2588:0x2591);}
void ansi_flush(void){if(!initialized||!dirty)return;for(unsigned y=0;y<height;y++)for(unsigned x=0;x<width;x++){unsigned i=y*MW+x;if(front[i].cp!=back[i].cp||front[i].attr!=back[i].attr){display_set_cell(x,y,cp437(back[i].cp),back[i].attr);front[i]=back[i];}}display_cursor_set(col,row,cursor_visible,1);dirty=0;}
