#include <os64/terminal.h>
#include <os64/libc.h>
#include <string.h>
#define MAX_CELLS (80u*25u)
struct term_cell{uint32_t cp;uint8_t fg,bg,dirty;};struct os_terminal{const os64_api_t*api;unsigned width,height;uint8_t fg,bg,owned;struct term_cell cells[MAX_CELLS];};static const os64_api_t*system_api;static struct os_terminal singleton;
static uint32_t decode(const unsigned char **s){uint32_t c=*(*s)++;if(c<128)return c;if((c&0xe0)==0xc0){uint32_t b=*(*s)++;return (c&31)<<6|(b&63);}if((c&0xf0)==0xe0){uint32_t b=*(*s)++,d=*(*s)++;return (c&15)<<12|(b&63)<<6|(d&63);}return '?';}
int os_init(const os64_api_t*api){if(!api||api->version<5)return 0;os64_libc_init(api);system_api=api;return 1;}os_terminal_t*os_terminal_create(void){if(!system_api||!system_api->terminal_acquire||!system_api->terminal_acquire())return 0;memset(&singleton,0,sizeof singleton);singleton.api=system_api;singleton.owned=1;singleton.width=system_api->terminal_width();singleton.height=system_api->terminal_height();if(singleton.width>80)singleton.width=80;if(singleton.height>25)singleton.height=25;singleton.fg=7;for(unsigned i=0;i<singleton.width*singleton.height;i++){singleton.cells[i].cp=' ';singleton.cells[i].fg=7;singleton.cells[i].dirty=1;}return &singleton;}
void os_terminal_destroy(os_terminal_t*t){if(t&&t->owned){t->api->terminal_cursor(0,0,0,1);t->api->terminal_release();t->owned=0;}}
void os_terminal_clear(os_terminal_t*t){if(!t)return;for(unsigned i=0;i<t->width*t->height;i++){t->cells[i].cp=' ';t->cells[i].fg=t->fg;t->cells[i].bg=t->bg;t->cells[i].dirty=1;}}
void os_terminal_set_color(os_terminal_t*t,uint8_t f,uint8_t b){if(t){t->fg=f&15;t->bg=b&15;}}
void os_terminal_put(os_terminal_t*t,unsigned x,unsigned y,uint32_t cp){if(!t||x>=t->width||y>=t->height)return;struct term_cell*c=&t->cells[y*t->width+x];if(c->cp!=cp||c->fg!=t->fg||c->bg!=t->bg){c->cp=cp;c->fg=t->fg;c->bg=t->bg;c->dirty=1;}}
void os_terminal_write(os_terminal_t*t,unsigned x,unsigned y,const char*text){if(!t||!text)return;const unsigned char*p=(const unsigned char*)text;while(*p&&x<t->width)os_terminal_put(t,x++,y,decode(&p));}
void os_terminal_box(os_terminal_t*t,unsigned x,unsigned y,unsigned w,unsigned h,int d){if(!t||w<2||h<2)return;uint32_t hz=d?0x2550:0x2500,vt=d?0x2551:0x2502,tl=d?0x2554:0x250c,tr=d?0x2557:0x2510,bl=d?0x255a:0x2514,br=d?0x255d:0x2518;for(unsigned i=1;i+1<w;i++){os_terminal_put(t,x+i,y,hz);os_terminal_put(t,x+i,y+h-1,hz);}for(unsigned i=1;i+1<h;i++){os_terminal_put(t,x,y+i,vt);os_terminal_put(t,x+w-1,y+i,vt);}os_terminal_put(t,x,y,tl);os_terminal_put(t,x+w-1,y,tr);os_terminal_put(t,x,y+h-1,bl);os_terminal_put(t,x+w-1,y+h-1,br);}
void os_terminal_panel(os_terminal_t*t,unsigned x,unsigned y,unsigned w,unsigned h,const char*title){os_terminal_box(t,x,y,w,h,0);if(title)os_terminal_write(t,x+2,y,title);}void os_terminal_progress(os_terminal_t*t,unsigned x,unsigned y,unsigned w,unsigned p){if(p>100)p=100;for(unsigned i=0;i<w;i++)os_terminal_put(t,x+i,y,i<w*p/100?0x2588:0x2591);}void os_terminal_statusbar(os_terminal_t*t,const char*s){if(!t||!t->height)return;uint8_t f=t->fg,b=t->bg;os_terminal_set_color(t,0,7);for(unsigned x=0;x<t->width;x++)os_terminal_put(t,x,t->height-1,' ');os_terminal_write(t,0,t->height-1,s);os_terminal_set_color(t,f,b);}
void os_terminal_flush(os_terminal_t*t){if(!t||!t->owned)return;for(unsigned y=0;y<t->height;y++)for(unsigned x=0;x<t->width;x++){struct term_cell*c=&t->cells[y*t->width+x];if(c->dirty){t->api->terminal_write_cell(x,y,c->cp,(uint8_t)((c->bg<<4)|(c->fg&15)));c->dirty=0;}}}
int os_terminal_run(os_terminal_t*t){if(!t)return -1;os_terminal_flush(t);for(;;){unsigned k=t->api->terminal_read_key();if(k==27||k==0x8a)return 0;}}
